# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/oouxx/fqsub/master/sub.list

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://i.sqeven.me/discuss/detail/100

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://lightyearapp.life/zh/free-vpn