# tg频道抓取
- type: tgchannel
  options:
    channel: NetfreexSrV
    num: 100
- type: tgchannel
  options:
    channel: SSRSUB
    num: 100
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 100
- type: tgchannel
  options:
    channel: V2List
    num: 100
- type: tgchannel
  options:
    channel: ssrtool
    num: 100
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 100
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 100
- type: tgchannel
  options:
    channel: fanqiang666
    num: 100
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 100
- type: tgchannel
  options:
    channel: ssrshares
    num: 100
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 100
- type: tgchannel
  options:
    channel: moneyfly01
    num: 100
- type: tgchannel
  options:
    channel: ssrv2taytgshare
    num: 100
- type: tgchannel
  options:
    channel: gyjclub
    num: 100
- type: tgchannel
  options:
    channel: TgProxies
    num: 100
- type: tgchannel
  options:
    channel: VPNFolder
    num: 100
- type: tgchannel
  options:
    channel: vmesssr
    num: 100
- type: tgchannel
  options:
    channel: youmtp
    num: 100
- type: tgchannel
  options:
    channel: ssrkn
    num: 100
- type: tgchannel
  options:
    channel: abchz
    num: 100
- type: tgchannel
  options:
    channel: yg251153
    num: 100
- type: tgchannel
  options:
    channel: woyaofq
    num: 100
- type: tgchannel
  options:
    channel: wwx_com
    num: 100
- type: tgchannel
  options:
    channel: freessr4k
    num: 100
- type: tgchannel
  options:
    channel: ultrafreevpn
    num: 100
- type: tgchannel
  options:
    channel: VSshit
    num: 100
- type: tgchannel
  options:
    channel: InternetSSR
    num: 100
- type: tgchannel
  options:
    channel: baipiaodadui
    num: 100
- type: tgchannel
  options:
    channel: mtproxy666
    num: 100
- type: tgchannel
  options:
    channel: v2ray666
    num: 100
- type: tgchannel
  options:
    channel: ssrList
    num: 100
- type: tgchannel
  options:
    channel: aifenxiang2020
    num: 100
- type: tgchannel
  options:
    channel: sharecentre
    num: 100
- type: tgchannel
  options:
    channel: SuperFastProxy
    num: 100
- type: tgchannel
  options:
    channel: proxypools
    num: 100
- type: tgchannel
  options:
    channel: ssList
    num: 100
- type: tgchannel
  options:
    channel: ssrlists
    num: 300
- type: tgchannel
  options:
    channel: FreeSSR666
    num: 100
- type: tgchannel
  options:
    channel: QuantXSSR
    num: 100
- type: tgchannel
  options:
    channel: huhihuhihi
    num: 100
- type: tgchannel
  options:
    channel: Ch_baipiao
    num: 100
- type: tgchannel
  options:
    channel: MTPdaili
    num: 100
- type: tgchannel
  options:
    channel: ripao1
    num: 100
- type: tgchannel
  options:
    channel: vmessr_mirror
    num: 100
- type: tgchannel
  options:
    channel: FreeVPN8
    num: 100
- type: tgchannel
  options:
    channel: Xinana_awsl
    num: 100
- type: tgchannel
  options:
    channel: daolis_miao
    num: 100
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 100
- type: tgchannel
  options:
    channel: LoremProxies
    num: 100
- type: tgchannel
  options:
    channel: baipiaofuli
    num: 100