# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/oouxx/fqsub/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/doudoubinga/ceshi/blob/master/trash/base64-sub
- type: webfuzzsub
  options:
    url: https://github.com/JACKUSR2089/v2ray-subscribed   
- type: webfuzzsub
  options:
    url: https://github.com/pojiezhiyuanjun/freev2
- type: webfuzzsub
  options:
    url: https://github.com/woytu/notes-vuepress/blob/757206d5c10d112d56a3c789d5a622d4bcfe6375/System/%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F.md
- type: webfuzzsub
  options:
    url: http://proxypool.turinglabs.net/
- type: webfuzzsub
  options:
    url: https://github.com/doudoubinga/ceshi/blob/27cd627f3467bcd88ab4a92f0c44baabc53c7e73/trash/base64-sub
- type: webfuzzsub
  options:
    url: https://github.com/wechoice/wechoice.github.io/blob/eb7f35b85fb2c676c16598b258a17e05adb82718/main.html
 
# tg频道抓取
- type: tgchannel
  options:
    channel: NetfreexSrV
    num: 100
- type: tgchannel
  options:
    channel: SSRSUB
    num: 100
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 100
- type: tgchannel
  options:
    channel: V2List
    num: 100