# tg频道抓取
- type: tgchannel
  options:
    channel: NetfreexSrV
    num: 100
- type: tgchannel
  options:
    channel: SSRSUB
    num: 100
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 100
- type: tgchannel
  options:
    channel: V2List
    num: 100
- type: tgchannel
  options:
    channel: ssrtool
    num: 100
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 100
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 100
- type: tgchannel
  options:
    channel: fanqiang666
    num: 100
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 100
- type: tgchannel
  options:
    channel: ssrshares
    num: 100
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 100