# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/oouxx/fqsub/master/sub.list
- type: webfuzzsub
  options:
    url: https://github.com/doudoubinga/ceshi/blob/master/trash/base64-sub
- type: webfuzzsub
  options:
    url: https://github.com/JACKUSR2089/v2ray-subscribed   
- type: webfuzzsub
  options:
    url: https://github.com/pojiezhiyuanjun/freev2
- type: webfuzzsub
  options:
    url: https://github.com/wishcaiji/sublist/blob/main/suburl.txt

# 订阅链接
#- type: subscribe
#  options:
#    url: https://iwxf.netlify.app/
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/SSR.md
#- type: subscribe
#  options:
#    url: https://cdn.jsdelivr.net/gh/fqnews/bnews@latest/vs/v2.txt
#- type: subscribe
#  options:
#    url: https://gitea.com/proxypools/sub/raw/branch/main/clash/clash.yaml
#- type: subscribe
#  options:
#    url: https://gitea.com/proxypools/sub/raw/branch/main/clash/clashr.yaml
#- type: subscribe
#  options:
#    url: https://gitea.com/proxypools/sub/raw/branch/main/qx/qx.yaml
#- type: subscribe
#  options:
#    url: https://gitea.com/proxypools/sub/raw/branch/main/qx/q.yaml
#- type: subscribe
#  options:
#    url: https://gitea.com/proxypools/sub/raw/branch/main/loon/loon.yaml
#- type: subscribe
#  options:
#    url: https://gitea.com/proxypools/sub/raw/branch/main/sb/sb.yaml
#- type: subscribe
#  options:
#    url: https://gitea.com/proxypools/sub/raw/branch/main/ss/ss.txt
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/satrom/V2SSR/master/SSR/Day.txt
#- type: subscribe
#  options:
#    url: https://yehuang2.netlify.app
#- type: subscribe
#  options:
#    url: https://yehuang1.netlify.app
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/satrom/V2SSR/master/V2RAY/Sub.txt
#- type: subscribe
#  options:
#    url: https://share.dmca.gripe/v5m2iqWlBi1PVhB7.txt
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
#- type: subscribe
#  options:
#    url: https://jiang.netlify.com/
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub
#- type: subscribe
#  options:
#    url: https://raw.githubusercontent.com/cdp2020/v2ray/master/README.md
#- type: subscribe
#  options:
#    url: https://gooii.ml/v2ray/sub
#- type: subscribe
#  options:
#    url: https://youlianboshi.netlify.com/
#- type: subscribe
#  options:
#    url: https://v2ray.banyunxiaoxi.ml/

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://i.sqeven.me/discuss/detail/100
- type: webfuzz
  options:
    url: https://i.sqeven.me/discuss/detail/102
- type: webfuzz
  options:
    url: https://github.com/umelabs/node.umelabs.dev
- type: webfuzz
  options:
    url: https://github.com/freefq/free
- type: webfuzz
  options:
    url: https://github.com/iwxf/free-v2ray/blob/master/README.md
- type: webfuzz
  options:
    url: https://github.com/hugetiny/awesome-vpn/blob/master/READMECN.md

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
- type: clash
  options:
    url: https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/0304clash.yml
- type: clash
  options:
    url: https://bihai.cf/clash/proxies
- type: clash
  options:
    url: https://upan.tk/clash/proxies
- type: clash
  options:
    url: https://freemby.tk/clash/proxies
- type: clash
  options:
    url: https://proxypoolv2.tk/clash/proxies
- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies
- type: clash
  options:
    url: https://hm2019721.ml/clash/proxies
- type: clash
  options:
    url: https://6166888.xyz/clash/proxies
- type: clash
  options:
    url: https://sspool.nl/clash/proxies
- type: clash
  options:
    url: https://hello.stgod.com/clash/proxies
- type: clash
  options:
    url: https://proxypool.ednovas.xyz/clash/proxies

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://lightyearapp.life/zh/free-vpn
  
# tg频道抓取
- type: tgchannel
  options:
    channel: NetfreexSrV
    num: 100
- type: tgchannel
  options:
    channel: SSRSUB
    num: 100
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 100
- type: tgchannel
  options:
    channel: V2List
    num: 100
- type: tgchannel
  options:
    channel: ssrtool
    num: 100
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 100
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 100
- type: tgchannel
  options:
    channel: fanqiang666
    num: 100
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 100
- type: tgchannel
  options:
    channel: ssrshares
    num: 100
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 100
- type: tgchannel
  options:
    channel: moneyfly01
    num: 100
- type: tgchannel
  options:
    channel: ssrv2taytgshare
    num: 100
- type: tgchannel
  options:
    channel: gyjclub
    num: 100
- type: tgchannel
  options:
    channel: TgProxies
    num: 100
- type: tgchannel
  options:
    channel: VPNFolder
    num: 100
- type: tgchannel
  options:
    channel: vmesssr
    num: 100
- type: tgchannel
  options:
    channel: youmtp
    num: 100
- type: tgchannel
  options:
    channel: ssrkn
    num: 100
- type: tgchannel
  options:
    channel: abchz
    num: 100
- type: tgchannel
  options:
    channel: yg251153
    num: 100
- type: tgchannel
  options:
    channel: woyaofq
    num: 100
- type: tgchannel
  options:
    channel: wwx_com
    num: 100
- type: tgchannel
  options:
    channel: freessr4k
    num: 100
- type: tgchannel
  options:
    channel: ultrafreevpn
    num: 100
- type: tgchannel
  options:
    channel: VSshit
    num: 100
- type: tgchannel
  options:
    channel: InternetSSR
    num: 100
