# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://github.com/JACKUSR2089/v2ray-subscribed   
- type: webfuzzsub
  options:
    url: https://github.com/woytu/notes-vuepress/blob/757206d5c10d112d56a3c789d5a622d4bcfe6375/System/%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F.md
- type: webfuzzsub
  options:
    url: https://github.com/doudoubinga/ceshi/blob/27cd627f3467bcd88ab4a92f0c44baabc53c7e73/trash/base64-sub
- type: webfuzzsub
  options:
    url: https://github.com/wechoice/wechoice.github.io/blob/eb7f35b85fb2c676c16598b258a17e05adb82718/main.html
 
# tg频道抓取
- type: tgchannel
  options:
    channel: SSRSUB
    num: 100
- type: tgchannel
  options:
    channel: FreeSSRNode
    num: 100
- type: tgchannel
  options:
    channel: ssrtool
    num: 100
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
- type: tgchannel
  options:
    channel: jiedianfenxiang
    num: 100
- type: tgchannel
  options:
    channel: fanqiang666
    num: 100
- type: tgchannel
  options:
    channel: ssrtool_crack
    num: 100
- type: tgchannel
  options:
    channel: gongyijichangfenxiang
    num: 200
- type: tgchannel
  options:
    channel: VPNFolder
    num: 100
- type: tgchannel
  options:
    channel: ssrkn
    num: 100
- type: tgchannel
  options:
    channel: abchz
    num: 100
- type: tgchannel
  options:
    channel: yg251153
    num: 100
- type: tgchannel
  options:
    channel: woyaofq
    num: 200
- type: tgchannel
  options:
    channel: wwx_com
    num: 100
- type: tgchannel
  options:
    channel: freessr4k
    num: 100
- type: tgchannel
  options:
    channel: ultrafreevpn
    num: 100
- type: tgchannel
  options:
    channel: VSshit
    num: 100
- type: tgchannel
  options:
    channel: InternetSSR
    num: 200
- type: tgchannel
  options:
    channel: mtproxy666
    num: 100
- type: tgchannel
  options:
    channel: v2ray666
    num: 100
- type: tgchannel
  options:
    channel: ssrList
    num: 100
- type: tgchannel
  options:
    channel: aifenxiang2020
    num: 100
- type: tgchannel
  options:
    channel: sharecentre
    num: 100
- type: tgchannel
  options:
    channel: ssrlists
    num: 200
- type: tgchannel
  options:
    channel: QuantXSSR
    num: 100
- type: tgchannel
  options:
    channel: vmessr_mirror
    num: 100
- type: tgchannel
  options:
    channel: FreeVPN8
    num: 100
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 200